//******************************************************************************
//* File:   BackgroundSubtractor.cpp
//* Author: Jon Newman <jpnewman snail mit dot edu>
//*
//* Copyright (c) Jon Newman (jpnewman snail mit dot edu)
//* All right reserved.
//* This file is part of the Oat project.
//* This is free software: you can redistribute it and/or modify
//* it under the terms of the GNU General Public License as published by
//* the Free Software Foundation, either version 3 of the License, or
//* (at your option) any later version.
//* This software is distributed in the hope that it will be useful,
//* but WITHOUT ANY WARRANTY; without even the implied warranty of
//* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//* GNU General Public License for more details.
//* You should have received a copy of the GNU General Public License
//* along with this source code.  If not, see <http://www.gnu.org/licenses/>.
//******************************************************************************

#include "OatConfig.h" // Generated by CMake

#include <string>
#include <iostream>
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>

#include <cpptoml.h>
#include "../../lib/utility/TOMLSanitize.h"
#include "../../lib/utility/IOFormat.h"

#include "BackgroundSubtractor.h"

namespace oat {

BackgroundSubtractor::BackgroundSubtractor(
            const std::string &frame_source_address,
            const std::string &frame_sink_address) :
  FrameFilter(frame_source_address, frame_sink_address)
{
    // Nothing
}

void BackgroundSubtractor::configure(const std::string& config_file, const std::string& config_key) {

    // Available options
    std::vector<std::string> options {"background", "adaption-coeff"};

    // This will throw cpptoml::parse_exception if a file
    // with invalid TOML is provided
    auto config = cpptoml::parse_file(config_file);

    // See if a camera configuration was provided
    if (config->contains(config_key)) {

        // Get this components configuration table
        auto this_config = config->get_table(config_key);

        // Check for unknown options in the table and throw if you find them
        oat::config::checkKeys(options, this_config);

        std::string background_img_path;
        if (oat::config::getValue(this_config, "background", background_img_path)) {
            background_frame_ = cv::imread(background_img_path, CV_LOAD_IMAGE_COLOR);

            if (background_frame_.data == NULL) {
                throw (std::runtime_error("File \"" + background_img_path + "\" could not be read."));
            }

            background_set_ = true;
        }

        // Learning coefficient
        oat::config::getValue(this_config, "adaption-coeff", alpha_, 0.0, 1.0);

    } else {
        throw (std::runtime_error(oat::configNoTableError(config_key, config_file)));
    }
}

void BackgroundSubtractor::setBackgroundImage(const cv::Mat &frame) {

    background_frame_ = frame.clone();
    frame.clone().convertTo(background_frame_f_, CV_32F);
    background_set_ = true;
}

void BackgroundSubtractor::filter(cv::Mat &frame) {

    // First image is always used as the default background image if one is
    // not provided in a configuration file
    if (!background_set_)
        setBackgroundImage(frame);

    if (alpha_ > 0.0) {
       cv::accumulateWeighted(frame, background_frame_f_, alpha_); 
       background_frame_f_.convertTo(background_frame_, CV_8U);
    }
        
    frame = frame - background_frame_;
}

} /* namespace oat */
