//******************************************************************************
//* File:   oat calibrate main.cpp
//* Author: Jon Newman <jpnewman snail mit dot edu>
//
//* Copyright (c) Jon Newman (jpnewman snail mit dot edu) 
//* All right reserved.
//* This file is part of the Oat project.
//* This is free software: you can redistribute it and/or modify
//* it under the terms of the GNU General Public License as published by
//* the Free Software Foundation, either version 3 of the License, or
//* (at your option) any later version.
//* This software is distributed in the hope that it will be useful,
//* but WITHOUT ANY WARRANTY; without even the implied warranty of
//* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//* GNU General Public License for more details.
//* You should have received a copy of the GNU General Public License
//* along with this source code.  If not, see <http://www.gnu.org/licenses/>.
//****************************************************************************

#include "OatConfig.h" // Generated by CMake

#include <iostream>
#include <csignal>
#include <unordered_map>
#include <boost/program_options.hpp>
#include <opencv2/core.hpp>

#include "../../lib/utility/IOFormat.h"
#include "../../lib/cpptoml/cpptoml.h"

#include "Calibrator.h"
//#include "CameraParameterGenerator.h"
#include "HomographyGenerator.h"

namespace po = boost::program_options;

volatile sig_atomic_t quit = 0;
volatile sig_atomic_t source_eof = 0;

void printUsage(po::options_description options){
    std::cout << "Usage: calibrate [INFO]\n"
              << "   or: calibrate SOURCE [CONFIGURATION]\n"
              << "Generate camera calibration and homography transform for a "
              << "frame SOURCE.\n\n"
              << "TYPE\n"
              << "  cal: Generate calibration parameters (camera matrix and distortion coefficients).\n"
              << "  homo: Generate homography transform between pixels and world units.\n\n"
              << "SOURCE:\n"
              << "  User-supplied name of the memory segment to receive frames "
              << "from (e.g. raw).\n\n"
              << options << "\n";
}

// Signal handler to ensure shared resources are cleaned on exit due to ctrl-c
void sigHandler(int s) {
    quit = 1;
}

// Processing loop
void run(const std::shared_ptr<Calibrator>& calibrator) {

    while (!quit && !source_eof) {
        source_eof = calibrator->process();
    }
}

int main(int argc, char *argv[]) {

    std::signal(SIGINT, sigHandler);

    std::string type;
    std::string source;
    std::string save_path;
    std::string config_file;
    std::string config_key;
    bool config_used = false;
    po::options_description visible_options("OPTIONS");

    std::unordered_map<std::string, char> type_hash;
    type_hash["cal"] = 'a';
    type_hash["homo"] = 'b';
    
    try {

        po::options_description options("INFO");
        options.add_options()
                ("help", "Produce help message.")
                ("version,v", "Print version information.")
                ;
        
        po::options_description config("CONFIGURATION");
        config.add_options()
                ("calibration-path,f", po::value<std::string>(&save_path),
                "The base configuration file location.\n"
                "The timestamp of the calibration will be prepended to th name."
                "If not provided, the calibration info will be printed to STDOUT.")
                ("config-file,c", po::value<std::string>(&config_file), "Configuration file.")
                ("config-key,k", po::value<std::string>(&config_key), "Configuration key.")
                ;

        po::options_description hidden("HIDDEN OPTIONS");
        hidden.add_options()
                ("type", po::value<std::string>(&type), 
                "Type of frame calibrator to use.\n\n"
                "Values:\n"
                "  cal: Generate calibration parameters (camera matrix and distortion coefficients).\n"
                "  homo: Generate homography transform between pixels and world units.")
                ("source", po::value<std::string>(&source),
                "The name of the SOURCE that supplies images on which to perform background subtraction."
                "The server must be of type SMServer<SharedCVMatHeader>\n")
                ;

        po::positional_options_description positional_options;
        positional_options.add("type", 1);
        positional_options.add("source", 1);
        
        visible_options.add(options).add(config);

        po::options_description all_options("All options");
        all_options.add(options).add(config).add(hidden);

        po::variables_map variable_map;
        po::store(po::command_line_parser(argc, argv)
                .options(all_options)
                .positional(positional_options)
                .run(),
                variable_map);
        po::notify(variable_map);

        // Use the parsed options
        if (variable_map.count("help")) {
            printUsage(visible_options);
            return 0;
        }

        if (variable_map.count("version")) {
            std::cout << "Oat calibrator version "
                      << Oat_VERSION_MAJOR
                      << "." 
                      << Oat_VERSION_MINOR 
                      << "\n";
            std::cout << "Written by Jonathan P. Newman in the MWL@MIT.\n";
            std::cout << "Licensed under the GPL3.0.\n";
            return 0;
        }
        
        if (!variable_map.count("type")) {
            printUsage(visible_options);
            std::cout << oat::Error("A TYPE must be specified.\n");
            return -1;
        }

        if (!variable_map.count("source")) {
            printUsage(visible_options);
            std::cout << oat::Error("A SOURCE must be specified.\n");
            return -1;
        }

        if ((variable_map.count("config-file") && !variable_map.count("config-key")) ||
                (!variable_map.count("config-file") && variable_map.count("config-key"))) {
            printUsage(visible_options);
            std::cerr << oat::Error("A configuration file must be supplied with a corresponding config-key.\n");
            return -1;
        } else if (variable_map.count("config-file")) {
            config_used = true;
        }

    } catch (std::exception& e) {
        std::cerr << oat::Error(e.what()) << "\n";
        return -1;
    } catch (...) {
        std::cerr << oat::Error("Exception of unknown type.\n");
        return -1;
    }

    // Create component
    std::shared_ptr<Calibrator> calibrator;
    
    // Refine component type
    switch (type_hash[type]) {
//        case 'a':
//        {
//            calibrator = std::make_shared<CameraParameterGenerator>(source);
//            break;
//        }
        case 'b':
        {
            calibrator = std::make_shared<HomographyGenerator>(source);
            break;
        }
        default:
        {
            printUsage(visible_options);
            std::cerr << oat::Error("Invalid TYPE specified.\n");
            return -1;
        }
    }
    
    // The business
    try { 
        
        if (config_used)
            calibrator->configure(config_file, config_key);

        // Tell user
        std::cout << oat::whoMessage(calibrator->name(),
                "Listening to source " + oat::sourceText(source) + ".\n")
                << oat::whoMessage(calibrator->name(),
                "Press CTRL+C to exit.\n");

        // Infinite loop until ctrl-c or end of stream signal
        run(calibrator);

        // Tell user
        std::cout << oat::whoMessage(calibrator->name(), "Exiting.\n");
        
        // Exit success
        return 0;

    } catch (const cpptoml::parse_exception& ex) {
        std::cerr << oat::whoError(calibrator->name(), 
                     "Failed to parse configuration file " 
                     + config_file + "\n")
                  << oat::whoError(calibrator->name(), ex.what())
                  << "\n";
    } catch (const std::runtime_error ex) {
        std::cerr << oat::whoError(calibrator->name(),ex.what())
                  << "\n";
    } catch (const cv::Exception ex) {
        std::cerr << oat::whoError(calibrator->name(), ex.what())
                  << "\n";
    } catch (...) {
        std::cerr << oat::whoError(calibrator->name(), "Unknown exception.\n");
    }
    
    // Exit failure
    return -1;
}
