//******************************************************************************
//* File:   oat record main.cpp
//* Author: Jon Newman <jpnewman snail mit dot edu>
//
//* Copyright (c) Jon Newman (jpnewman snail mit dot edu)
//* All right reserved.
//* This file is part of the Oat project.
//* This is free software: you can redistribute it and/or modify
//* it under the terms of the GNU General Public License as published by
//* the Free Software Foundation, either version 3 of the License, or
//* (at your option) any later version.
//* This software is distributed in the hope that it will be useful,
//* but WITHOUT ANY WARRANTY; without even the implied warranty of
//* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//* GNU General Public License for more details.
//* You should have received a copy of the GNU General Public License
//* along with this source code.  If not, see <http://www.gnu.org/licenses/>.
//****************************************************************************

// TODO: I'm having a hard time getting decent exit behavior out of this program
// in ineractive mode. The problem is
// 1. source_eof = recorder->writeStreams(); blocks forever unless it sees a SIGINT
// 2. when using interactive mode, SIGINTs from the user (Ctrl+C) have no effect becase
//    std::cin blocks until it gets user input. I have not found an adequate way to unblock
//    the STDIN stream.
// The result is that the user always has to do two things: type 'exit' and hit Ctrl+C to
// exit the program in interactive mode.

#include "OatConfig.h" // Generated by CMake

#include <algorithm>
#include <csignal>
#include <future>
#include <memory>
#include <unordered_map>
#include <string>
#include <boost/program_options.hpp>

#include "../../lib/utility/IOFormat.h"
#include "../../lib/utility/IOUtility.h"

#include "Recorder.h"

namespace po = boost::program_options;

volatile sig_atomic_t quit = 0;
volatile sig_atomic_t source_eof = 0;

// Interactive commands
bool recording_on = true;
bool interactive = false;

void printUsage(std::ostream& out, po::options_description options) {
    out << "Usage: record [INFO]\n"
        << "   or: record [CONFIGURATION]\n"
        << "Record frame and/or position streams.\n\n"
        << options << "\n";
}

// TODO: Fix
void printInteractiveUsage(std::ostream& out) {

    out << "COMMANDS\n"
        << "CMD         FUNCTION\n"
        << "  h         Print this information.\n"
        << "  r         Toggle recording on and off.\n"
        << "            TODO...\n"
        << "  n         Start new file.\n"
        << "            TODO...\n"
        << "  N         Specify a new file location.\n"
        << "            reconstruction error will be printed.\n\n";
}

// Signal handler to ensure shared resources are cleaned on exit due to ctrl-c
void sigHandler(int) {

    // Interactive mode requires "exit"
    //if (!interactive)
        quit = 1;
}

// Processing loop
void run(std::shared_ptr<oat::Recorder>& recorder) {
    try {

        recorder->connectToNodes();

        while (!quit && !source_eof) {
            source_eof = recorder->writeStreams();
        }

    } catch (const boost::interprocess::interprocess_exception &ex) {

        // Error code 1 indicates a SIGINT during a call to wait(), which
        // is normal behavior
        if (ex.get_error_code() != 1)
            throw;
    }
}

int interact() {

    // Command map
    std::unordered_map<std::string, char> cmd_map;
    cmd_map["exit"] = 'e';
    cmd_map["help"] = 's';
    cmd_map["start"] = 's';
    cmd_map["stop"] = 'S';
    cmd_map["new"] = 'n';
    cmd_map["move"] = 'm';

    // User control loop
    std::string cmd;

    while (!quit) {

        std::cout << ">>> ";
        std::getline(std::cin, cmd);
        //if (!(std::cin >> cmd))
        //    oat::ignoreLine(std::cin);

        switch (cmd_map[cmd]) {
            case 's' :
            {
                // Toggle record on/off
                recording_on = true;
                std::cout << "Recording ON.\n";
                break;
            }
            case 'S' :
            {
                // Toggle record on/off
                recording_on = false;
                std::cout << "Recording OFF.\n";
                break;
            }
            case 'e' :
            {
                quit = 1;
                break;
            }
            default :
            {
                // Flush cin in case the uer just inserted crap
                oat::ignoreLine(std::cin);
                std::cerr << "Invalid command \'" << cmd << "\'\n";
                break;
            }
        }
    }

    return 0;
}

int main(int argc, char *argv[]) {

    std::signal(SIGINT, sigHandler);

    std::vector<std::string> frame_sources;
    std::vector<std::string> position_sources;
    std::string file_name;
    std::string save_path;
    bool allow_overwrite = false;
    int fps = 30; //TODO: This should be sent with the frames
    bool append_date = false;

    try {

        po::options_description options("INFO");
        options.add_options()
                ("help", "Produce help message.")
                ("version,v", "Print version information.")
                ;

        po::options_description configuration("CONFIGURATION");
        configuration.add_options()
                ("filename,n", po::value<std::string>(&file_name),
                "The base file name to which to source name will be appended")
                ("folder,f", po::value<std::string>(&save_path),
                "The path to the folder to which the video stream and position information will be saved.")
                ("date,d",
                "If specified, YYYY-MM-DD-hh-mm-ss_ will be prepended to the filename.")
                ("allow-overwrite,o",
                "If set and save path matches and existing file, the file will be overwritten instead of"
                "a numerical index being added to the file path.")
                ("position-sources,p", po::value< std::vector<std::string> >()->multitoken(),
                "The names of the POSITION SOURCES that supply object positions to be recorded.")
                ("interactive,i", "Start recorder with interactive controls enabled.")
                ("frame-sources,s", po::value< std::vector<std::string> >()->multitoken(),
                "The names of the FRAME SOURCES that supply images to save to video.")
                ("frames-per-second,F", po::value<int>(&fps),
                "The frame rate of the recorded video. This determines playback speed of the recording. "
                "It does not affect online processing in any way.\n")
                ;

        po::options_description all_options("OPTIONS");
        all_options.add(options).add(configuration);

        po::variables_map variable_map;
        po::store(po::command_line_parser(argc, argv)
                .options(all_options)
                .run(),
                variable_map);
        po::notify(variable_map);

        // Use the parsed options
        if (variable_map.count("help")) {
            printUsage(std::cout, all_options);
            return 0;
        }

        if (variable_map.count("version")) {
            std::cout << "Oat Recorder version "
                      << Oat_VERSION_MAJOR
                      << "."
                      << Oat_VERSION_MINOR
                      << "\n";
            std::cout << "Written by Jonathan P. Newman in the MWL@MIT.\n";
            std::cout << "Licensed under the GPL3.0.\n";
            return 0;
        }

        if (!variable_map.count("position-sources") && !variable_map.count("frame-sources")) {
            printUsage(std::cout, all_options);
            std::cerr << oat::Error("At least a single POSITION SOURCE or FRAME SOURCE must be specified.\n");
            return -1;
        }

        if (!variable_map.count("folder")) {
            save_path = ".";
            std::cerr << oat::Warn("Warning: Saving files to the current directory.\n");
        }

        if (!variable_map.count("filename")) {
            file_name = "";
            std::cerr << oat::Warn("Warning: No base filename was provided.\n");
        }

        if (variable_map.count("interactive")) {
            interactive = true;
        }

        if (!variable_map.count("frames-per-second") && variable_map.count("frame-sources")) {
            fps = 30;
            std::cerr << oat::Warn("Warning: Video playback speed set to 30 FPS.\n");
        }

        // May contain imagesource and sink information!]
        if (variable_map.count("position-sources")) {
            position_sources = variable_map["position-sources"].as< std::vector<std::string> >();

            // Assert that all positions sources are unique. If not, remove duplicates, and issue warning.
            std::vector<std::string>::iterator it;
            it = std::unique (position_sources.begin(), position_sources.end());
            if (it != position_sources.end()) {
                position_sources.resize(std::distance(position_sources.begin(),it));
                std::cerr << oat::Warn("Warning: duplicate position sources have been removed.\n");
            }
        }

        if (variable_map.count("frame-sources")) {
            frame_sources = variable_map["frame-sources"].as< std::vector<std::string> >();

            // Assert that all positions sources are unique. If not, remove duplicates, and issue warning.
            std::vector<std::string>::iterator it;
            it = std::unique (frame_sources.begin(), frame_sources.end());
            if (it != frame_sources.end()) {
                frame_sources.resize(std::distance(frame_sources.begin(),it));
                 std::cerr << oat::Warn("Warning: duplicate frame sources have been removed.\n");
            }
        }

        if (variable_map.count("date")) {
            append_date = true;
        }

        if (variable_map.count("allow-overwrite")) {
            allow_overwrite = true;
        }


    } catch (std::exception& e) {
        std::cerr << oat::Error(e.what()) << "\n";
        return -1;
    } catch (...) {
        std::cerr << oat::Error("Exception of unknown type.\n");
        return -1;
    }

    // Create component
    auto recorder = std::make_shared<oat::Recorder>(position_sources,
                                                    frame_sources,
                                                    save_path,
                                                    file_name,
                                                    append_date,
                                                    fps,
                                                    allow_overwrite);

    // Tell user
    if (!frame_sources.empty()) {

        std::cout << oat::whoMessage(recorder->name(),
                "Listening to frame sources ");

        for (auto s : frame_sources)
            std::cout << oat::sourceText(s) << " ";

        std::cout << ".\n";
    }

    if (!position_sources.empty()) {

        std::cout << oat::whoMessage(recorder->name(),
                "Listening to position sources ");

        for (auto s : position_sources)
            std::cout << oat::sourceText(s) << " ";

        std::cout << ".\n";
    }

    std::cout << oat::whoMessage(recorder->name(),
                 "Press CTRL+C to exit.\n");

    // The business
    try {

        if (interactive) {

            // Launch async IO thread
            auto usr_io = std::async(std::launch::async, []{ interact(); });

            // Start the recorder
            run(recorder);

            // Join recorder and UI threads
            if (usr_io.valid()) {
                usr_io.wait();
            } else {
                std::error_code ec;
                throw std::future_error(ec);
            }

        } else {

            // Start the recorder
            run(recorder);
        }

        // Tell user
        std::cout << oat::whoMessage(recorder->name(), "Exiting.\n");

        // Exit
        return 0;

    } catch (const std::future_error &ex) {
        std::cerr << oat::whoError(recorder->name(), ex.what()) << "\n";
    } catch (const std::runtime_error &ex) {
        std::cerr << oat::whoError(recorder->name(), ex.what()) << "\n";
    } catch (const cv::Exception &ex) {
        std::cerr << oat::whoError(recorder->name(), ex.what()) << "\n";
    } catch (const boost::interprocess::interprocess_exception &ex) {
        std::cerr << oat::whoError(recorder->name(), ex.what()) << "\n";
    } catch (...) {
        std::cerr << oat::whoError(recorder->name(), "Unknown exception.\n");
    }

    // Exit failure
    return -1;
}
